<?php

namespace Sf\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Sf\UserBundle\Entity\User;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends EntityRepository {

    public function get(User $user = null, $type) {
        return $this->createQueryBuilder('e')
                        ->where('e.type=:type')
                        ->andWhere('e.account =:account')
                        ->setParameter('account', $user != null ? $user->getId() : null)
                        ->setParameter('type', $type)
                        ->getQuery()
                        ->getOneOrNullResult();
    }

    public function getPriorityAddress(User $user = null) {
        $billing = $this->createQueryBuilder('e')
                ->where('e.type=:type')
                ->andWhere('e.account =:account')
                ->setParameter('account', $user != null ? $user->getId() : null)
                ->setParameter('type', 'billing')
                ->getQuery()
                ->getOneOrNullResult();
        if ($billing == null) {
            $shipping = $this->createQueryBuilder('e')
                    ->where('e.type=:type')
                    ->andWhere('e.account =:account')
                    ->setParameter('account', $user != null ? $user->getId() : null)
                    ->setParameter('type', 'shipping')
                    ->getQuery()
                    ->getOneOrNullResult();

            return $shipping;
        } else {
            return $billing;
        }
    }

}
