<?php

namespace Sf\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * ProductModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualityRepository extends EntityRepository {

  
    
     public function getDates() {
     
        $data = $this->createQueryBuilder('e')
                ->distinct()
                ->select('e.year')
                ->andWhere('e.active = true')
                
                ->orderBy('e.date', 'desc')
                ->getQuery()
                ->getArrayResult();

        return $data;
    }

 

}
