<?php

namespace Sf\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository {

    public function getActiveQueryBuilder() {
        return $this->createQueryBuilder('g')
                        ->where('g.active = true')
                        ->andWhere('g.deleted = false')
                        ->orderBy('g.name', 'asc')
                        ;
    }

}
