<?php

namespace Sf\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Sf\AdminBundle\Entity\Order;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailRepository extends EntityRepository
{
  public function get(Order $order){
      
      return $this->createQueryBuilder('e')
              ->where('e.order =:order')
              ->setParameter('order', $order->getId())
              ->orderBy('e.sendAt', 'desc')
              ->getQuery()
              ->getResult();
  }
}
