<?php

namespace Sf\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Sf\AdminBundle\Entity\Order;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderBrandRepository extends EntityRepository {

    public function getBrands(Order $order) {
        return $this->createQueryBuilder('e')
                        //->select('e,b')
                        ->distinct('e.id')
                        ->where('e.order =:order')
                        ->innerJoin('e.brand', 'b')
                        ->setParameter('order', $order->getId())
                        ->orderBy('b.name', 'asc')
                        ->getQuery()
                        ->getResult();
    }

}
