<?php

namespace Sf\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Sf\UserBundle\Entity\User;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends EntityRepository {

    public function get(User $user = null,$status = null) {
        $qb = $this->createQueryBuilder('e')
                ->leftJoin('e.orderStatus', 's');


        if($status == null){
         $qb->where('e.status !=:status') ->setParameter('status', 'New');
        }else{
           $qb->where('e.status =:status') ->setParameter('status',$status);  
        }
               
        
          $qb      ->orderBy('e.orderDate', 'desc');

        if ($user != null) {
            $qb->andWhere('e.account=:user')->setParameter('user', $user->getId());
        }

        return $qb->getQuery()
                        ->getResult();
    }
    
    

}
