<?php

namespace Sf\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizeRepository extends EntityRepository
{
  
}
