
    
fos_user_security_login:
    path:  /login
    defaults: { _controller: FOSUserBundle:Security:login }
    options:
        i18n: false

fos_user_security_check:
    path:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements: { _method: POST }
    options:
        i18n: false
   
account:
    path: /mon-compte/{message}
    defaults: { _controller: "SfAdminBundle:Account:index", message: null }
    
orders:
    path: /les-commandes
    defaults: { _controller: "SfAdminBundle:Order:index", message: null }
    
control:
    path:     /control
    defaults: { _controller: "SfAdminBundle:Account:control" }
    options: { i18n: false }

order_orders:
    path:     /les-commandes/{number}
    defaults: { _controller: "SfAdminBundle:Order:orders",number:0 }

order_update:
    path:     /order/update/{order}/{number}
    defaults: { _controller: "SfAdminBundle:Order:update" ,number:0}
    options:
        expose: true
        
order_load_shoppingcart:
    path:     /order/load-shopping-cart/{order}
    defaults: { _controller: "SfAdminBundle:Order:loadShoppingCart"}
    options: { i18n: false,expose: true }

mail_update:
    path:     /mail/{order}/{number}
    defaults: { _controller: "SfAdminBundle:Mail:update" ,number:0}
    options:
        expose: true
        i18n: false
        
address:
    path:     /address/{type}/{redirect}
    defaults: { _controller: "SfAdminBundle:Account:address", redirect: null }
    options:
        i18n: false

shop_order_validate:
    path:     /shop/order/validate
    defaults: { _controller: "SfAdminBundle:Order:validate" }
    options:
        i18n: false

invoice_download:
    path:  invoice/download/{invoice}
    defaults: { _controller: "SfAdminBundle:Invoice:dowload" }

admin_partner:
    path:  /admin/clubs-et-partenaires
    defaults: { _controller: "SfAdminBundle:Partner:index" }
        
admin_partner_update:
    path:  /admin/clubs-et-partenaires/mise-a-jour/{partner}
    defaults: { _controller: "SfAdminBundle:Partner:update",partner: null }

admin_config:
    path:  /admin/configuration
    defaults: { _controller: "SfAdminBundle:Config:index" }

admin_group:
    path:  /group/{brand}
    defaults: { _controller: "SfAdminBundle:Group:index" }
    options: { i18n_prefix: admin }

admin_group_update:
    path:  /group/update/{brand}/{id}
    defaults: { _controller: "SfAdminBundle:Group:update", id : null}
    options: { i18n_prefix: admin }


admin_product:
    path:  /admin/produits
    defaults: { _controller: "SfAdminBundle:Product:index"}

admin_product_update:
    path:  /admin/produits/mis-à-jours/{id}
    defaults: { _controller: "SfAdminBundle:Product:update", id : null}


admin_product_model:
    path:  /admin/modèles-du-produit/{product}
    defaults: { _controller: "SfAdminBundle:ProductModel:index"}
    requirements:
        { _method: get, product:  \d+ }

admin_product_model_expose:
    path:  /admin/product-model/{product}
    defaults: { _controller: "SfAdminBundle:ProductModel:index"}
    requirements:
        { _method: get, product:  \d+ }
    options:
        expose: true

admin_product_model_stock:
    path:  /admin/modèles-du-produit/stock/{product}
    defaults: { _controller: "SfAdminBundle:ProductModel:stock", product : null}
    requirements:
        { _method: get|post, product:  \d+ }
        
admin_product_model_update:
    path:  /admin/product-model/update/{number}
    defaults: { _controller: "SfAdminBundle:ProductModel:update"}
    requirements:
        productModel:  \d+
           
admin_product_model_delete:
    path:  /admin/product-model/delete
    defaults: { _controller: "SfAdminBundle:ProductModel:delete", _locale: fr}
    options:
        expose: true
        

    
admin_accounts:
    path:  /les-comptes
    defaults: { _controller: "SfAdminBundle:Account:list" }

admin_accounts_list:
    path:     /les-comptes/liste
    defaults: { _controller: "SfAdminBundle:Account:accountslist" }
    options: { i18n_prefix: admin,expose : true, i18n: false}
    
admin_account_update:
    path:     /les-comptes/mise-a-jour/{user}
    defaults: { _controller: "SfAdminBundle:Account:update" , user :null}
    options: { expose : true, i18n: false}
    
admin_about_us:
    path:     /admin/about-us
    defaults: { _controller: "SfAdminBundle:AboutUs:index"}

admin_legals:
    path:     /admin/mentions-légales
    defaults: { _controller: "SfAdminBundle:Legal:index"}
    
admin_press:
    path:     /admin/presse
    defaults: { _controller: "SfAdminBundle:Press:index"}
    
admin_press_update:
    path:     /admin/press/update/{press}
    defaults: { _controller: "SfAdminBundle:Press:update",press:null}
    
admin_pub:
    path:     /admin/pub
    defaults: { _controller: "SfAdminBundle:Pub:index"}
    
admin_pub_update:
    path:     /admin/pub/update/{pub}
    defaults: { _controller: "SfAdminBundle:Pub:update",pub:null}
    
admin_carrousel:
    path:     /admin/carrousel
    defaults: { _controller: "SfAdminBundle:Carrousel:index"}
    
admin_carrousel_update:
    path:     /admin/carrousel/update/{carrousel}
    defaults: { _controller: "SfAdminBundle:Carrousel:update",carrousel:null}

admin_category:
    path:     /admin/categorie
    defaults: { _controller: "SfAdminBundle:Category:index"}
    
admin_category_update:
    path:     /admin/categorie/update/{cat}
    defaults: { _controller: "SfAdminBundle:Category:update",cat:null}
    
admin_catalog:
    path:     /admin/catalogue
    defaults: { _controller: "SfAdminBundle:Catalog:index"}

admin_catalog_club:
    path:     /admin/catalogue/club
    defaults: { _controller: "SfAdminBundle:Catalog:club"}

admin_catalog_press:
    path:     /admin/catalogue/press
    defaults: { _controller: "SfAdminBundle:Catalog:press"}

admin_actuality:
    path:     /admin/actus
    defaults: { _controller: "SfAdminBundle:Actuality:index"}

admin_actuality_update:
    path:     /admin/actus/update/{actuality}
    defaults: { _controller: "SfAdminBundle:Actuality:update",actuality:null}
    
admin_brand:
    path:     /admin/brand
    defaults: { _controller: "SfAdminBundle:Brand:index"}
    
admin_criterion:
    path:     /critères
    defaults: { _controller: "SfAdminBundle:Criterion:index"}
    options: { i18n_prefix: admin }
    

admin_criterion_update:
    path:     /critère/{type}/{id}
    defaults: { _controller: "SfAdminBundle:Criterion:update", id:null, type:null}
    options: { i18n_prefix: admin }
    

 
 
 