security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_EDIT_USER ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me:  true
                always_use_default_target_path : true
                default_target_path: /control
                use_referer : true
            remember_me:
                key:          %secret%
            logout:
                path: fos_user_security_logout
                target: /login
                invalidate_session: false
            anonymous:    true



    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: [ROLE_ADMIN] }
        - { path: ^/mon-compte, role: [ROLE_CUSTOMER,ROLE_ADMIN] }
        - { path: ^/order, role: [ROLE_CUSTOMER,ROLE_SHOP,ROLE_ADMIN] }
        - { path: ^/orders, role: [ROLE_CUSTOMER,ROLE_SHOP,ROLE_ADMIN] }
        - { path: ^/shop/order/validate, role: [ROLE_SHOP,ROLE_ADMIN] }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
